name: 'Build and test'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: Test
        run: ./test.sh
